dist: bionic
language: generic
before_install:
- |
  echo "Checking if a CI run is needed post commit: ${TRAVIS_COMMIT_RANGE}"
  if ! git diff --name-only ${TRAVIS_COMMIT_RANGE} | grep -qvE '(\.png$)|(\.pdf$)|(\.html$)|^(LICENSE)'
  then
    echo "Only doc files were updated, not running the CI."
    exit
  fi
- sudo add-apt-repository --yes ppa:js-reynaud/kicad-5.1
- sudo apt update -y
- sudo apt install --no-install-recommends -y kicad kicad-symbols kicad-templates
  kicad-footprints inkscape
script:
- cd scripts && ./pcb2svg.sh && cd ..
before_deploy:
- git config --local user.name "PCB Gerber Exporter"
- git config --local user.email "noreply@w4xzr.xyz"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
- ls
- ls Gerbers/
deploy:
  provider: releases
  api_key:
    secure: n3ywSMIsNJYXmqYaqJdqpM/W+nZ3luecUmdid6APyrlBJf+84xCRIfXIO6Q4jbETlkpzkwJ4CY/hPaxRDGGTVNmCY1SZciLDXZnTNMAosdOr+Npy1e7BNV3o9eORhHT/LyPuaInJKlvcUvcnDlA6DMIhLYwMUtjSXc7sW32U28HFR3A7LlHqVL9BNmyjufgDa0SoyHagvcxLbY0FTzEeYXBk9+iOM8zs7kNhWenxApZEhUR5n6bhJr5G2daYIIeCiany0bCYmGVu3CBqwrs4iRJx2OyugERa6mw65AnJA47pOWXoq2IjHRg7Sr3e4qCrv70Pqd2pA9WyWyzVQa9nbYS732+Q+eGmXtd8aBW+Jf4Ko4vHQz/ftrB25iByNLgQ84N6FOz9qHtCJnDcopxO2AN2Pm9tGERORaRKyWT8VZ0BpEfKn79vUO44i394p9jqAZ7Q/iciSEWDj+izK0hmBDOnLyx1oFnLi6KMd67A7as9l6cit4KdvDUCxBxw/U74n39PgMIbrGbgeR0YBlrYV7qWOWOe3VCio419VH5schCTGBbuTusv2FmFjALEhzNjB048PBZ6vcuiRun1B4qhZmJuy602+30IbGk1j44Tcg0IslFGwyIhqnIUOhMvbOynveus16hhXiKkFdYqa9xOTqSBnydmzh/KDsl9hnEcY2E=
  file: Gerbers/PRO-117_gerbers.zip
  on:
    repo: w4xzr/PRO-117
  skip_cleanup: 'true'
